CC 					:= 	arm-linux-gnueabihf-g++

CFLAGS			:= 	-I/opt/cross/rpi/rootfs/usr/include \
			    			-I/opt/cross/rpi/rootfs/usr/include/arm-linux-gnueabihf/

LDFLAGS 		:= 	-L/opt/cross/rpi/rootfs/usr/lib

.PHONY: all
all: i2c

i2c: i2c.cpp
	$(CC) $(CFLAGS) $^ $(LDFLAGS) -o $@
